# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: root

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - https://github.com/kellymears.keys
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - https://github.com/kellymears.keys
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.3-fpm *"
